let audioIds = [];
audioIds [0] = 'CQACAgIAAxkBAAOZXwMqSDdUDpABMIjrnMwNBv3lFBAAApkGAAJ4vxlI8LIB-RMvgxYaBA'

audioIds [1] = 'CQACAgIAAxkBAAObXwMq57seZ8U1qMqb1rlYZXL7VqAAApsGAAJ4vxlIA0sszPg57CcaBA'

audioIds [2] = 'CQACAgIAAxkBAAOdXwMrHgE2hprsOVwvzfX1pLYY3FIAApwGAAJ4vxlIS2oaz6THINkaBA'

audioIds [3] = 'CQACAgIAAxkBAAOfXwMrVHep3qHRLXuamRnrHMVupbEAAp0GAAJ4vxlILlR-nYQxBN8aBA'

audioIds [4] = 'CQACAgIAAxkBAAOhXwMrdfRHp8wuWv5136adR-wwtDMAAp4GAAJ4vxlIeU5kmpM8PwEaBA'

audioIds [5] = 'CQACAgIAAxkBAAOjXwMrnI6CTRzn1rkIr9Tx8T6JC78AAp8GAAJ4vxlIL_-CalB-y7kaBA'

audioIds [6] = 'CQACAgIAAxkBAAOlXwMrxO0UgLTVMQo9v78PcVpbAr8AAqAGAAJ4vxlIB7HN2p9mmLUaBA'

audioIds [7] = 'CQACAgIAAxkBAAOnXwMr7xoYDe65XiG4rY3KQbKmaUwAAqEGAAJ4vxlI60jTKDktKo8aBA'

audioIds [8] = 'CQACAgIAAxkBAAOpXwMsB8EdfMLyJjWlMMCaxwZ0mmUAAqMGAAJ4vxlIYsmqvoaAaqMaBA'

audioIds [9] = 'CQACAgIAAxkBAAOrXwMsJhwBTkTQVN40SlCsLkxyJwMAAqQGAAJ4vxlI7Ui8IylsWzgaBA'

audioIds [10] = 'CQACAgIAAxkBAAOtXwMsQwpMFVPz-15lRm7TW_xdtGsAAqUGAAJ4vxlIhY42f3ku3NQaBA'

audioIds [11] = 'CQACAgIAAxkBAAOvXwMsYd7R824MwIfiTEwGH6Eru1kAAqYGAAJ4vxlIWVRSKUnjP-8aBA'

audioIds [12] = 'CQACAgIAAxkBAAOxXwMse6hejjFPaxkVMv39Y-Tan08AAqcGAAJ4vxlI8Lq-wv0pjMwaBA'

audioIds [13] = 'CQACAgIAAxkBAAOzXwMskkOq9Ho6vzkjjjbj07iVmzYAAqgGAAJ4vxlIYMzSYQtVXywaBA'

audioIds [14] = 'CQACAgIAAxkBAAO1XwMsqxVlR7MiIwtUFuJfB39jg3oAAqkGAAJ4vxlI8hPnVMKnQ_EaBA'

audioIds [15] = 'CQACAgIAAxkBAAO3XwMsxW7bBT6U64RbX5Zlatuqh8oAAqoGAAJ4vxlIubayan0ER_EaBA'

audioIds [16] = 'CQACAgIAAxkBAAO5XwMs5GiiqN1DuVASLjJoJ-52PDIAAqsGAAJ4vxlIJbm1uETvU7YaBA'

audioIds [17] = 'CQACAgIAAxkBAAO7XwMtAAEOz1iuf0egJ9nJvDkXaqg_AAKsBgACeL8ZSK5o9srf8DKjGgQ'

audioIds [18] = 'CQACAgIAAxkBAAO9XwMtHSWLOQaCC6y3Ll_HF2nfzz4AAq0GAAJ4vxlIfy0eE5sqsJEaBA'

audioIds [19] = 'CQACAgIAAxkBAAO_XwMtOLR9SWkpqaJoJqpEBS2MyBsAAq4GAAJ4vxlIZCFbM-PbQlYaBA'

audioIds [20] = 'CQACAgIAAxkBAAPBXwMtVZ2Ge0uhkzQtzLnW06h28uoAAq8GAAJ4vxlI7cbc4tGJvkEaBA'


module.exports = audioIds